import { prepareMenuSections, renderShogunMenu } from "./presentation.js";

const sections = [
    { title: "TUTORIAL DO BOT", icon: "✨", entries: [
        {"command":"tutorial", "description":"Consultar as instruções de configuração do bot."},
    ] },
    { title: "CONFIGURAÇÕES DO BOT", icon: "🪄", optionKey: "botConfigMenuTitle", entries: [
        {"command":"prefixo", "description":"Alterar o prefixo padrão do bot."},
        {"command":"numerodono", "description":"Configurar o contato do dono da instância."},
        {"command":"nomedono"},
        {"command":"nomebot", "description":"Alterar o nome de exibição do bot."},
        {"command":"configcmdnotfound"},
        {"command":"setcmdmsg"},
        {"command":"fotobot"},
        {"command":"fotomenu"},
        {"command":"videomenu"},
        {"command":"audiomenu"},
        {"command":"lermais"},
        {"command":"personalizargrupo"},
    ] },
    { title: "APARÊNCIA DOS MENUS", icon: "🎨", optionKey: "menuDesignMenuTitle", entries: [
        {"command":"designmenu", "description":"Consultar e configurar a aparência dos menus."},
        {"command":"setborda"},
        {"command":"setbordafim"},
        {"command":"setbordameio"},
        {"command":"setitem"},
        {"command":"setseparador"},
        {"command":"settitulo"},
        {"command":"setheader"},
        {"command":"resetdesign", "description":"Restaurar o design padrão dos menus."},
    ] },
    { title: "MENSAGENS PROMOCIONAIS", icon: "✨", entries: [
        { command: "defmsgpromo", arguments: "<mensagem>", description: "Salvar a mensagem promocional e obter seu ID." },
        { command: "listmsgpromo", description: "Consultar mensagens promocionais e progresso dos envios." },
        { command: "sendmsgpromo", arguments: "<id>", description: "Agendar o envio gradual da mensagem aos grupos." },
    ] },
    { title: "AUTOMAÇÕES & REAÇÕES", icon: "⚙️", optionKey: "automationMenuTitle", entries: [
        {"command":"addauto"},
        {"command":"addautomidia"},
        {"command":"listauto"},
        {"command":"delauto"},
        {"command":"addreact"},
        {"command":"listreact"},
        {"command":"delreact"},
        {"command":"addnopref"},
        {"command":"listnopref"},
        {"command":"delnopref"},
    ] },
    { title: "PERSONALIZAÇÃO DE COMANDOS", icon: "✨", optionKey: "commandCustomMenuTitle", entries: [
        {"command":"addcmd"},
        {"command":"addcmdmidia"},
        {"command":"listcmd"},
        {"command":"delcmd"},
        {"command":"testcmd"},
        {"command":"addalias", "description":"Cadastrar um nome alternativo para um comando."},
        {"command":"listalias", "description":"Consultar os aliases cadastrados."},
        {"command":"delalias"},
        {"command":"addblackglobal"},
        {"command":"listblackglobal"},
        {"command":"rmblackglobal"},
    ] },
    { title: "LIMITAÇÃO DE COMANDOS", icon: "✨", optionKey: "commandLimitingMenuTitle", entries: [
        {"command":"cmdlimitar"},
        {"command":"cmddeslimitar"},
        {"command":"cmdlimites", "description":"Consultar os limites de uso dos comandos."},
    ] },
    { title: "SUBDONOS & PREMIUM", icon: "⚙️", optionKey: "userManagementMenuTitle", entries: [
        {"command":"addsubdono"},
        {"command":"delsubdono"},
        {"command":"listasubdonos", "description":"Listar subdonos da instância."},
        {"command":"addpremium"},
        {"command":"delpremium"},
        {"command":"listprem", "description":"Listar usuários premium."},
        {"command":"resetgold"},
    ] },
    { title: "INDICAÇÕES & BLOQUEIO DE GRUPOS", icon: "✨", entries: [
        {"command":"addindicacao"},
        {"command":"topindica"},
        {"command":"delindicacao"},
        {"command":"bangp"},
        {"command":"unbangp"},
        {"command":"listbangp"},
    ] },
    { title: "SISTEMA DE ALUGUEL", icon: "🪙", optionKey: "rentalSystemMenuTitle", entries: [
        {"command":"modoaluguel"},
        {"command":"addaluguel"},
        {"command":"gerarcod"},
        {"command":"listaraluguel"},
        {"command":"infoaluguel"},
        {"command":"estenderaluguel"},
        {"command":"removeraluguel"},
        {"command":"listaluguel"},
        {"command":"limparaluguel"},
        {"command":"dayfree"},
        {"command":"setdiv"},
        {"command":"divulgar"},
    ] },
    { title: "GERENCIAMENTO DE SUB-BOTS", icon: "⚙️", optionKey: "subBotsMenuTitle", entries: [
        {"command":"addsubbot"},
        {"command":"removesubbot"},
        {"command":"listarsubbots", "description":"Consultar os sub-bots cadastrados."},
        {"command":"conectarsubbot"},
    ], notes: ["No sub-bot, use #prefix#gerarcodigo."] },
    { title: "CONTROLE & MANUTENÇÃO", icon: "🛡️", optionKey: "botControlMenuTitle", entries: [
        {"command":"atualizar"},
        {"command":"reiniciar"},
        {"command":"entrar"},
        {"command":"sairgp"},
        {"command":"seradm"},
        {"command":"sermembro"},
        {"command":"blockcmdg"},
        {"command":"unblockcmdg"},
        {"command":"blockuserg"},
        {"command":"unblockuserg"},
        {"command":"listblocks", "description":"Consultar bloqueios globais."},
        {"command":"antibanmarcar"},
        {"command":"imagem"},
    ] },
    { title: "CONSULTAS & CONTROLES GLOBAIS", icon: "✨", optionKey: "monitoringMenuTitle", entries: [
        {"command":"listagp", "description":"Listar os grupos do bot."},
        {"command":"antipv"},
        {"command":"antipv2"},
        {"command":"antipv3"},
        {"command":"antipv4"},
        {"command":"antipvmsg"},
        {"command":"antispamcmd"},
        {"command":"viewmsg"},
        {"command":"cases"},
        {"command":"getcase"},
        {"command":"modoliteglobal", "description":"Configurar o modo lite global."},
        {"command":"iaclear"},
        {"command":"limpardb"},
        {"command":"limparrankg"},
        {"command":"reviverqr"},
        {"command":"nuke"},
        {"command":"msgprefix"},
    ] },
    { title: "TRANSMISSÃO EM GRUPOS", icon: "✨", entries: [
        {"command":"tm"},
    ] },
    { title: "TRANSMISSÃO NO PRIVADO", icon: "✨", entries: [
        {"command":"tm2"},
        {"command":"statustm"},
    ], notes: ["Inscrição pelo privado: #prefix#inscrevertm."] },
    { title: "DIVULGAÇÃO DO DONO", icon: "✨", entries: [
        {"command":"divdono","arguments":"add"},
        {"command":"divdono","arguments":"rem"},
        {"command":"divdono","arguments":"list"},
        {"command":"divdono","arguments":"msg"},
        {"command":"divdono","arguments":"send"},
        {"command":"divdono","arguments":"time"},
        {"command":"divdono","arguments":"status"},
    ] },
];

export default async function menuDono(prefix, _botName = "SHOGUN", userName = "Usuário", options = {}) {
    return renderShogunMenu({
        intro: "Configuração da instância, automações, acesso e manutenção.",
        footer: "Para consultar o design dos menus, use #prefix#menudesign.",
        options,
        title: "GESTÃO DO BOT", prefix, userName,
        sections: prepareMenuSections(sections, options),
    });
}
