import { prepareMenuSections, renderShogunMenu } from "./presentation.js";

const sections = [
    { title: "PERSONAGEM & RANKINGS", icon: "👤", optionKey: "profileMenuTitle", entries: [
        {"command":"perfilrpg", "description":"Consultar nível e atributos do personagem."},
        {"command":"carteira", "description":"Consultar seu saldo no RPG."},
        {"command":"toprpg"},
        {"command":"rankglobal"},
        {"command":"ranklvl"},
        {"command":"inv", "description":"Consultar os itens do inventário."},
        {"command":"equipamentos", "description":"Consultar seus equipamentos."},
        {"command":"conquistas"},
    ] },
    { title: "EVOLUÇÃO & PRESTÍGIO", icon: "⚔️", optionKey: "evolutionMenuTitle", entries: [
        {"command":"evoluir"},
        {"command":"prestige"},
        {"command":"streak"},
        {"command":"reivindicar"},
        {"command":"speedup"},
    ] },
    { title: "BANCO, LOJA & EMPREGO", icon: "🪙", optionKey: "economyMenuTitle", entries: [
        {"command":"dep","arguments":"<valor|all>", "description":"Depositar moedas no banco do RPG."},
        {"command":"sacar","arguments":"<valor|all>", "description":"Retirar moedas do banco do RPG."},
        {"command":"pix","arguments":"@user <valor>", "description":"Transferir moedas para outro jogador."},
        {"command":"loja"},
        {"command":"comprar","arguments":"<item>"},
        {"command":"vender","arguments":"<item> <qtd>"},
        {"command":"vagas", "description":"Consultar vagas de emprego no RPG."},
        {"command":"emprego","arguments":"<vaga>", "description":"Escolher uma vaga de emprego."},
        {"command":"demitir"},
        {"command":"habilidades"},
        {"command":"desafiosemanal"},
        {"command":"desafiomensal"},
    ] },
    { title: "INVESTIMENTOS & BOLSA", icon: "🪙", optionKey: "investmentMenuTitle", entries: [
        {"command":"investir"},
        {"command":"investir","arguments":"<ação> <qtd>"},
        {"command":"sell","arguments":"<ação> <qtd>"},
    ] },
    { title: "CASSINO & APOSTAS", icon: "🪙", optionKey: "gamblingMenuTitle", entries: [
        {"command":"dados","arguments":"<valor>"},
        {"command":"coinflip","arguments":"<cara|coroa> <valor>"},
        {"command":"crash","arguments":"<valor>"},
        {"command":"slots","arguments":"<valor>"},
        {"command":"apostar","arguments":"<valor>"},
        {"command":"roleta","arguments":"<valor> <cor>"},
        {"command":"blackjack","arguments":"<valor>"},
        {"command":"loteria"},
        {"command":"loteria","arguments":"comprar <qtd>"},
        {"command":"corrida","arguments":"<valor> <cavalo>"},
        {"command":"leilao"},
        {"command":"topriqueza"},
    ] },
    { title: "ATIVIDADES DIÁRIAS", icon: "📝", optionKey: "activitiesMenuTitle", entries: [
        {"command":"diario"},
        {"command":"work"},
        {"command":"mine"},
        {"command":"fish"},
        {"command":"coletar"},
        {"command":"colher"},
        {"command":"caçar"},
        {"command":"plantar","arguments":"<planta>"},
        {"command":"cultivar","arguments":"<planta>"},
        {"command":"plantacao"},
        {"command":"cook","arguments":"<receita>"},
        {"command":"receitas"},
        {"command":"ingredientes"},
        {"command":"eat","arguments":"<comida>"},
        {"command":"vendercomida","arguments":"<item>"},
        {"command":"sementes"},
    ] },
    { title: "AVENTURA & EXPLORAÇÃO", icon: "⚔️", optionKey: "adventureMenuTitle", entries: [
        {"command":"explore"},
        {"command":"masmorra"},
        {"command":"bossrpg"},
        {"command":"eventos"},
    ] },
    { title: "MASMORRAS EM GRUPO", icon: "⚔️", entries: [
        {"command":"dungeon","description":"Consultar as masmorras disponíveis."},
        {"command":"dungeon","arguments":"criar <tipo>", "description":"Criar uma masmorra do tipo indicado."},
        {"command":"dungeon","arguments":"entrar <id>", "description":"Entrar na masmorra pelo ID."},
        {"command":"dungeon","arguments":"iniciar", "description":"Iniciar a masmorra com os participantes."},
        {"command":"dungeon","arguments":"sair", "description":"Sair da masmorra atual."},
    ] },
    { title: "CLASSES DO PERSONAGEM", icon: "⚔️", entries: [
        {"command":"class","description":"Consultar as classes disponíveis."},
        {"command":"class","arguments":"<nome>","description":"Escolher a classe do personagem."},
    ] },
    { title: "CASA & DECORAÇÃO", icon: "🏡", entries: [
        {"command":"casa","description":"Consultar sua casa no RPG."},
        {"command":"casa","arguments":"comprar <tipo>", "description":"Comprar uma casa do tipo indicado."},
        {"command":"casa","arguments":"coletar", "description":"Coletar os rendimentos da casa."},
        {"command":"casa","arguments":"decorar <item>", "description":"Decorar sua casa com o item indicado."},
    ] },
    { title: "MERCADO DE JOGADORES", icon: "🪙", entries: [
        {"command":"auction","description":"Consultar itens anunciados por jogadores."},
        {"command":"auction","arguments":"vender <item> <preço>", "description":"Anunciar um item pelo preço indicado."},
        {"command":"auction","arguments":"comprar <nº>", "description":"Comprar o item pelo número do anúncio."},
        {"command":"auction","arguments":"meus", "description":"Consultar seus anúncios."},
        {"command":"auction","arguments":"cancelar <nº>", "description":"Cancelar um dos seus anúncios."},
    ] },
    { title: "MERCADO GERAL", icon: "🪙", entries: [
        {"command":"mercado"},
        {"command":"listar","arguments":"<item> <preço>"},
        {"command":"cmerc","arguments":"<nº>"},
        {"command":"meusan"},
        {"command":"cancelar","arguments":"<nº>"},
    ] },
    { title: "COMBATE & BATALHAS", icon: "⚔️", optionKey: "combatMenuTitle", entries: [
        {"command":"duelrpg","arguments":"@user", "description":"Desafiar outro jogador para um duelo."},
        {"command":"arena"},
        {"command":"torneio"},
        {"command":"assaltar","arguments":"@user"},
        {"command":"crime"},
        {"command":"guerra"},
        {"command":"desafio"},
    ] },
    { title: "FORJA & EQUIPAMENTOS", icon: "✨", optionKey: "craftingMenuTitle", entries: [
        {"command":"forge","arguments":"<item>", "description":"Forjar o item indicado."},
        {"command":"enchant"},
        {"command":"dismantle","arguments":"<item>"},
        {"command":"reparar","arguments":"<item>"},
        {"command":"materiais"},
        {"command":"precos"},
    ] },
    { title: "SOCIAL & INTERAÇÕES", icon: "🎲", optionKey: "socialMenuTitle", entries: [
        {"command":"casar","arguments":"@user"},
        {"command":"divorciar"},
        {"command":"namorar","arguments":"@user"},
        {"command":"terminar"},
        {"command":"relacionamento"},
        {"command":"casais"},
        {"command":"abracarrpg","arguments":"@user"},
        {"command":"beijarrpg","arguments":"@user"},
        {"command":"baterrpg","arguments":"@user"},
        {"command":"proteger","arguments":"@user"},
    ] },
    { title: "FAMÍLIA & ADOÇÃO", icon: "🫶", optionKey: "familyMenuTitle", entries: [
        {"command":"familia"},
        {"command":"adotaruser","arguments":"@user"},
        {"command":"deserdar","arguments":"@user"},
        {"command":"arvore"},
    ] },
    { title: "CLÃS & CONVITES", icon: "✨", optionKey: "guildMenuTitle", entries: [
        {"command":"criarcla","arguments":"<nome>", "description":"Criar um clã com o nome indicado."},
        {"command":"cla"},
        {"command":"convidar","arguments":"@user"},
        {"command":"sair"},
        {"command":"aceitarconvite","arguments":"<clanId|nome>"},
        {"command":"recusarconvite","arguments":"<clanId|nome>"},
        {"command":"expulsar","arguments":"@user"},
        {"command":"rmconvite","arguments":"@user"},
    ] },
    { title: "MISSÕES & CONQUISTAS", icon: "🏆", optionKey: "questMenuTitle", entries: [
        {"command":"missoes", "description":"Consultar suas missões."},
        {"command":"conquistas"},
    ] },
    { title: "PETS, TREINO & BATALHAS", icon: "🐾", optionKey: "petsMenuTitle", entries: [
        {"command":"pets", "description":"Consultar seus pets."},
        {"command":"adotar","arguments":"<pet>"},
        {"command":"feed","arguments":"<nº>"},
        {"command":"train","arguments":"<nº>"},
        {"command":"evolve","arguments":"<nº>"},
        {"command":"petbattle","arguments":"<nº>"},
        {"command":"renamepet","arguments":"<nº> <nome>"},
        {"command":"petbet","arguments":"<valor> <nº> @user"},
        {"command":"equippet","arguments":"<nº> <nome do item>"},
        {"command":"unequippet","arguments":"<nº> <slot?>"},
    ] },
    { title: "REPUTAÇÃO & FAMA", icon: "✨", optionKey: "reputationMenuTitle", entries: [
        {"command":"rep"},
        {"command":"vote","arguments":"@user"},
    ] },
    { title: "EVENTOS", icon: "✨", optionKey: "eventsMenuTitle", entries: [
        {"command":"eventos"},
    ] },
    { title: "LOJA PREMIUM", icon: "🪙", optionKey: "premiumMenuTitle", entries: [
        {"command":"lojapremium"},
        {"command":"comprarpremium","arguments":"<item>"},
        {"command":"boost"},
        {"command":"propriedades"},
        {"command":"cprop","arguments":"<id>"},
        {"command":"cprops"},
        {"command":"tributos"},
        {"command":"meustats"},
        {"command":"doar","arguments":"<valor>"},
        {"command":"presente","arguments":"@user <item>"},
    ] },
    { title: "GESTÃO DO RPG", icon: "⚔️", optionKey: "adminMenuTitle", entries: [
        {"command":"rpgadd","arguments":"@user <valor>"},
        {"command":"rpgremove","arguments":"@user <valor>"},
        {"command":"rpgsetlevel","arguments":"@user <nivel>"},
        {"command":"rpgadditem","arguments":"@user <item> <qtd>"},
        {"command":"rpgremoveitem","arguments":"@user <item> <qtd>"},
        {"command":"rpgresetplayer","arguments":"@user", "description":"Zerar os dados do jogador indicado."},
        {"command":"rpgresetglobal","arguments":"confirmar", "description":"Zerar os dados globais do RPG após confirmação."},
        {"command":"rpgstats", "description":"Consultar estatísticas do RPG."},
    ] },
];

export default async function menuRPG(prefix, _botName = "SHOGUN", userName = "Usuário", options = {}) {
    return renderShogunMenu({
        intro: "Personagem, economia, missões, equipamentos e combate do RPG.",
        footer: "Consulte #prefix#perfilrpg para ver o personagem e #prefix#carteira para ver o saldo.",
        options,
        title: "RPG", prefix, userName,
        sections: prepareMenuSections(sections, options),
    });
}
