import { prepareMenuSections, renderShogunMenu } from "./presentation.js";

const sections = [
    { title: "INÍCIO", entries: [
        {"command":"tutorial"},
    ] },
    { title: "CONFIGURAÇÕES DO BOT", optionKey: "botConfigMenuTitle", entries: [
        {"command":"prefixo"},
        {"command":"numerodono"},
        {"command":"nomedono"},
        {"command":"nomebot"},
        {"command":"configcmdnotfound"},
        {"command":"setcmdmsg"},
        {"command":"fotobot"},
        {"command":"fotomenu"},
        {"command":"videomenu"},
        {"command":"audiomenu"},
        {"command":"lermais"},
        {"command":"personalizargrupo"},
    ] },
    { title: "DESIGN & APARÊNCIA", optionKey: "menuDesignMenuTitle", entries: [
        {"command":"designmenu"},
        {"command":"setborda"},
        {"command":"setbordafim"},
        {"command":"setbordameio"},
        {"command":"setitem"},
        {"command":"setseparador"},
        {"command":"settitulo"},
        {"command":"setheader"},
        {"command":"resetdesign"},
    ] },
    { title: "PROMOÇÕES", entries: [
        { command: "defmsgpromo", arguments: "<mensagem>", description: "Salva um texto e recebe um ID." },
        { command: "listmsgpromo", description: "Consulta textos e progresso do envio." },
        { command: "sendmsgpromo", arguments: "<id>", description: "Agenda o envio gradual aos grupos." },
    ] },
    { title: "SISTEMA & AUTOMAÇÃO", optionKey: "automationMenuTitle", entries: [
        {"command":"addauto"},
        {"command":"addautomidia"},
        {"command":"listauto"},
        {"command":"delauto"},
        {"command":"addreact"},
        {"command":"listreact"},
        {"command":"delreact"},
        {"command":"addnopref"},
        {"command":"listnopref"},
        {"command":"delnopref"},
    ] },
    { title: "PERSONALIZAÇÃO DE COMANDOS", optionKey: "commandCustomMenuTitle", entries: [
        {"command":"addcmd"},
        {"command":"addcmdmidia"},
        {"command":"listcmd"},
        {"command":"delcmd"},
        {"command":"testcmd"},
        {"command":"addalias"},
        {"command":"listalias"},
        {"command":"delalias"},
        {"command":"addblackglobal"},
        {"command":"listblackglobal"},
        {"command":"rmblackglobal"},
    ] },
    { title: "LIMITAÇÃO DE COMANDOS", optionKey: "commandLimitingMenuTitle", entries: [
        {"command":"cmdlimitar"},
        {"command":"cmddeslimitar"},
        {"command":"cmdlimites"},
    ] },
    { title: "GERENCIAMENTO DE USUÁRIOS", optionKey: "userManagementMenuTitle", entries: [
        {"command":"addsubdono"},
        {"command":"delsubdono"},
        {"command":"listasubdonos"},
        {"command":"addpremium"},
        {"command":"delpremium"},
        {"command":"listprem"},
        {"command":"resetgold"},
    ] },
    { title: "INDICAÇÕES", entries: [
        {"command":"addindicacao"},
        {"command":"topindica"},
        {"command":"delindicacao"},
        {"command":"bangp"},
        {"command":"unbangp"},
        {"command":"listbangp"},
    ] },
    { title: "SISTEMA DE ALUGUEL", optionKey: "rentalSystemMenuTitle", entries: [
        {"command":"modoaluguel"},
        {"command":"addaluguel"},
        {"command":"gerarcod"},
        {"command":"listaraluguel"},
        {"command":"infoaluguel"},
        {"command":"estenderaluguel"},
        {"command":"removeraluguel"},
        {"command":"listaluguel"},
        {"command":"limparaluguel"},
        {"command":"dayfree"},
        {"command":"setdiv"},
        {"command":"divulgar"},
    ] },
    { title: "GERENCIAMENTO DE SUB-BOTS", optionKey: "subBotsMenuTitle", entries: [
        {"command":"addsubbot"},
        {"command":"removesubbot"},
        {"command":"listarsubbots"},
        {"command":"conectarsubbot"},
    ], notes: ["No sub-bot, use #prefix#gerarcodigo."] },
    { title: "CONTROLE & MANUTENÇÃO", optionKey: "botControlMenuTitle", entries: [
        {"command":"atualizar"},
        {"command":"reiniciar"},
        {"command":"entrar"},
        {"command":"sairgp"},
        {"command":"seradm"},
        {"command":"sermembro"},
        {"command":"blockcmdg"},
        {"command":"unblockcmdg"},
        {"command":"blockuserg"},
        {"command":"unblockuserg"},
        {"command":"listblocks"},
        {"command":"antibanmarcar"},
        {"command":"imagem"},
    ] },
    { title: "MONITORAMENTO & ANÁLISE", optionKey: "monitoringMenuTitle", entries: [
        {"command":"listagp"},
        {"command":"antipv"},
        {"command":"antipv2"},
        {"command":"antipv3"},
        {"command":"antipv4"},
        {"command":"antipvmsg"},
        {"command":"antispamcmd"},
        {"command":"viewmsg"},
        {"command":"cases"},
        {"command":"getcase"},
        {"command":"modoliteglobal"},
        {"command":"iaclear"},
        {"command":"limpardb"},
        {"command":"limparrankg"},
        {"command":"reviverqr"},
        {"command":"nuke"},
        {"command":"msgprefix"},
    ] },
    { title: "TRANSMISSÃO EM GRUPOS", entries: [
        {"command":"tm"},
    ] },
    { title: "TRANSMISSÃO NO PRIVADO", entries: [
        {"command":"tm2"},
        {"command":"statustm"},
    ], notes: ["Inscrição pelo privado: #prefix#inscrevertm."] },
    { title: "DIVULGAÇÃO DO DONO", entries: [
        {"command":"divdono","arguments":"add"},
        {"command":"divdono","arguments":"rem"},
        {"command":"divdono","arguments":"list"},
        {"command":"divdono","arguments":"msg"},
        {"command":"divdono","arguments":"send"},
        {"command":"divdono","arguments":"time"},
        {"command":"divdono","arguments":"status"},
    ] },
];

export default async function menuDono(prefix, _botName = "SHOGUN", userName = "Usuário", options = {}) {
    return renderShogunMenu({
        title: "GESTÃO DO BOT", prefix, userName,
        sections: prepareMenuSections(sections, options),
    });
}
