import { prepareMenuSections, renderShogunMenu } from "./presentation.js";

const sections = [
    { title: "MODERAÇÃO DE MEMBROS", icon: "✨", optionKey: "adminMenuTitle", entries: [
        {"command":"ban", "description":"Remover um membro do grupo."},
        {"command":"ban2"},
        {"command":"bam","description":"Simular um banimento."},
        {"command":"setbammsg"},
        {"command":"promover", "description":"Tornar um membro administrador."},
        {"command":"rebaixar", "description":"Remover o cargo de administrador."},
        {"command":"mute", "description":"Silenciar um membro."},
        {"command":"desmute", "description":"Retirar o silenciamento de um membro."},
        {"command":"mute2"},
        {"command":"desmute2"},
        {"command":"adv", "description":"Registrar uma advertência."},
        {"command":"rmadv"},
        {"command":"listadv", "description":"Consultar as advertências registradas."},
        {"command":"limparrank"},
        {"command":"resetrank"},
        {"command":"mantercontador"},
        {"command":"atividade", "description":"Consultar a atividade de um membro."},
        {"command":"checkativo"},
    ] },
    { title: "CONTROLE DE ACESSO", icon: "🛡️", entries: [
        {"command":"blockuser"},
        {"command":"unblockuser"},
        {"command":"listblocksgp"},
        {"command":"addblacklist"},
        {"command":"delblacklist"},
        {"command":"listblacklist"},
        {"command":"blockcmd"},
        {"command":"unblockcmd"},
    ] },
    { title: "GESTÃO DO GRUPO", icon: "✨", optionKey: "managementMenuTitle", entries: [
        {"command":"del"},
        {"command":"limpar"},
        {"command":"marcar"},
        {"command":"hidetag"},
        {"command":"sorteio"},
        {"command":"nomegp"},
        {"command":"descgrupo"},
        {"command":"fotogrupo"},
        {"command":"addregra"},
        {"command":"delregra"},
        {"command":"role.criar"},
        {"command":"role.alterar"},
        {"command":"role.excluir"},
    ] },
    { title: "ACESSO & HORÁRIOS DO GRUPO", icon: "📝", entries: [
        {"command":"linkgp", "description":"Consultar o link de convite do grupo."},
        {"command":"grupo","arguments":"A/F", "description":"Abrir ou fechar o envio de mensagens no grupo."},
        {"command":"opengp","arguments":"HH:MM|off", "description":"Agendar a abertura do grupo ou desativar o horário."},
        {"command":"closegp","arguments":"HH:MM|off", "description":"Agendar o fechamento do grupo ou desativar o horário."},
        {"command":"automsg"},
        {"command":"banghost"},
        {"command":"limitmessage"},
        {"command":"dellimitmessage"},
    ] },
    { title: "SOLICITAÇÕES DE ENTRADA", icon: "✨", entries: [
        {"command":"solicitacoes", "description":"Listar pedidos de entrada no grupo."},
        {"command":"aprovar", "description":"Aprovar pedidos de entrada."},
        {"command":"aprovar","arguments":"all", "description":"Aprovar todos os pedidos de entrada pendentes."},
        {"command":"recusarsolic", "description":"Recusar um pedido de entrada."},
    ] },
    { title: "MODERADORES", icon: "🛡️", optionKey: "moderatorsMenuTitle", entries: [
        {"command":"addmod"},
        {"command":"delmod"},
        {"command":"listmods"},
        {"command":"grantmodcmd", "description":"Autorizar um comando para moderadores."},
        {"command":"revokemodcmd"},
        {"command":"listmodcmds", "description":"Consultar comandos permitidos aos moderadores."},
    ] },
    { title: "EXCEÇÕES ÀS PROTEÇÕES", icon: "🛡️", entries: [
        {"command":"wladd"},
        {"command":"wl.remove"},
        {"command":"wl.lista"},
    ] },
    { title: "PARCERIAS", icon: "✨", optionKey: "partnershipsMenuTitle", entries: [
        {"command":"parcerias"},
        {"command":"addparceria"},
        {"command":"delparceria"},
    ] },
    { title: "SEGURANÇA & PROTEÇÃO", icon: "🛡️", entries: [
        {"command":"antiflood"},
        {"command":"antidoc"},
        {"command":"antiloc"},
        {"command":"antifig"},
        {"command":"antibtn"},
        {"command":"antilinkgp"},
        {"command":"antilinkcanal"},
        {"command":"antilinkhard"},
        {"command":"antilinksoft"},
        {"command":"antiporn"},
        {"command":"antistatus"},
        {"command":"x9"},
        {"command":"captcha"},
        {"command":"antitoxic","arguments":"<on/off>", "description":"Ativar ou desativar a proteção contra mensagens tóxicas."},
        {"command":"antitoxic","arguments":"config <ação>", "description":"Definir a ação da proteção contra mensagens tóxicas."},
        {"command":"antitoxic","arguments":"sensibilidade <0-100>", "description":"Ajustar a sensibilidade da detecção de mensagens tóxicas."},
        {"command":"antipalavra","arguments":"<on/off/add/del/list>", "description":"Ativar a proteção e gerenciar palavras bloqueadas."},
    ] },
    { title: "BOAS-VINDAS, SAÍDAS & PREFIXO", icon: "🪄", optionKey: "settingsMenuTitle", entries: [
        {"command":"legendasaiu"},
        {"command":"legendabv"},
        {"command":"fotobv"},
        {"command":"bannerbv"},
        {"command":"rmfotobv"},
        {"command":"fotosaiu"},
        {"command":"bannersaiu"},
        {"command":"rmfotosaiu"},
        {"command":"setprefix", "description":"Alterar o prefixo do grupo."},
    ] },
    { title: "RESPOSTAS AUTOMÁTICAS", icon: "✨", entries: [
        {"command":"addautoadm"},
        {"command":"addautoadmidia"},
        {"command":"listautoadm"},
        {"command":"delautoadm"},
        {"command":"autorespostas"},
        {"command":"autorepo"},
    ] },
    { title: "MODOS DO GRUPO", icon: "✨", entries: [
        {"command":"autodl"},
        {"command":"minmessage"},
        {"command":"assistente"},
        {"command":"modobn"},
        {"command":"modoparceria"},
        {"command":"modorpg"},
        {"command":"modolite", "description":"Alternar o modo lite do grupo."},
        {"command":"bemvindo"},
        {"command":"saida"},
        {"command":"autosticker"},
        {"command":"soadm", "description":"Restringir o uso de comandos aos administradores."},
        {"command":"cmdlimit"},
        {"command":"fotomenugrupo"},
        {"command":"nomegp"},
        {"command":"infoperso"},
    ] },
];

export default async function menuadm(prefix, _botName = "SHOGUN", userName = "Usuário", options = {}) {
    return renderShogunMenu({
        intro: "Moderação de membros, proteções e ajustes do grupo.",
        footer: "Confira as regras atuais com #prefix#regras.",
        options,
        title: "ADMINISTRAÇÃO", prefix, userName,
        sections: prepareMenuSections(sections, options),
    });
}
