import { prepareMenuSections, renderShogunMenu } from "./presentation.js";

const sections = [
    { title: "GESTÃO DE USUÁRIOS", icon: "✨", optionKey: "adminMenuTitle", entries: [
        {"command":"ban"},
        {"command":"ban2"},
        {"command":"bam","description":"Simular um banimento."},
        {"command":"setbammsg"},
        {"command":"promover"},
        {"command":"rebaixar"},
        {"command":"mute"},
        {"command":"desmute"},
        {"command":"mute2"},
        {"command":"desmute2"},
        {"command":"adv"},
        {"command":"rmadv"},
        {"command":"listadv"},
        {"command":"limparrank"},
        {"command":"resetrank"},
        {"command":"mantercontador"},
        {"command":"atividade"},
        {"command":"checkativo"},
    ] },
    { title: "CONTROLE DE ACESSO", icon: "🛡️", entries: [
        {"command":"blockuser"},
        {"command":"unblockuser"},
        {"command":"listblocksgp"},
        {"command":"addblacklist"},
        {"command":"delblacklist"},
        {"command":"listblacklist"},
        {"command":"blockcmd"},
        {"command":"unblockcmd"},
    ] },
    { title: "GESTÃO DO GRUPO", icon: "✨", optionKey: "managementMenuTitle", entries: [
        {"command":"del"},
        {"command":"limpar"},
        {"command":"marcar"},
        {"command":"hidetag"},
        {"command":"sorteio"},
        {"command":"nomegp"},
        {"command":"descgrupo"},
        {"command":"fotogrupo"},
        {"command":"addregra"},
        {"command":"delregra"},
        {"command":"role.criar"},
        {"command":"role.alterar"},
        {"command":"role.excluir"},
    ] },
    { title: "GRUPO & PERMISSÕES", icon: "📝", entries: [
        {"command":"linkgp"},
        {"command":"grupo","arguments":"A/F"},
        {"command":"opengp","arguments":"HH:MM|off"},
        {"command":"closegp","arguments":"HH:MM|off"},
        {"command":"automsg"},
        {"command":"banghost"},
        {"command":"limitmessage"},
        {"command":"dellimitmessage"},
    ] },
    { title: "SOLICITAÇÕES", icon: "✨", entries: [
        {"command":"solicitacoes"},
        {"command":"aprovar"},
        {"command":"aprovar","arguments":"all"},
        {"command":"recusarsolic"},
    ] },
    { title: "MODERADORES", icon: "🛡️", optionKey: "moderatorsMenuTitle", entries: [
        {"command":"addmod"},
        {"command":"delmod"},
        {"command":"listmods"},
        {"command":"grantmodcmd"},
        {"command":"revokemodcmd"},
        {"command":"listmodcmds"},
    ] },
    { title: "EXCEÇÕES ÀS PROTEÇÕES", icon: "🛡️", entries: [
        {"command":"wladd"},
        {"command":"wl.remove"},
        {"command":"wl.lista"},
    ] },
    { title: "PARCERIAS", icon: "✨", optionKey: "partnershipsMenuTitle", entries: [
        {"command":"parcerias"},
        {"command":"addparceria"},
        {"command":"delparceria"},
    ] },
    { title: "SEGURANÇA & PROTEÇÃO", icon: "🛡️", entries: [
        {"command":"antiflood"},
        {"command":"antidoc"},
        {"command":"antiloc"},
        {"command":"antifig"},
        {"command":"antibtn"},
        {"command":"antilinkgp"},
        {"command":"antilinkcanal"},
        {"command":"antilinkhard"},
        {"command":"antilinksoft"},
        {"command":"antiporn"},
        {"command":"antistatus"},
        {"command":"x9"},
        {"command":"captcha"},
        {"command":"antitoxic","arguments":"<on/off>"},
        {"command":"antitoxic","arguments":"config <ação>"},
        {"command":"antitoxic","arguments":"sensibilidade <0-100>"},
        {"command":"antipalavra","arguments":"<on/off/add/del/list>"},
    ] },
    { title: "CONFIGURAÇÕES", icon: "🪄", optionKey: "settingsMenuTitle", entries: [
        {"command":"legendasaiu"},
        {"command":"legendabv"},
        {"command":"fotobv"},
        {"command":"bannerbv"},
        {"command":"rmfotobv"},
        {"command":"fotosaiu"},
        {"command":"bannersaiu"},
        {"command":"rmfotosaiu"},
        {"command":"setprefix"},
    ] },
    { title: "RESPOSTAS AUTOMÁTICAS", icon: "✨", entries: [
        {"command":"addautoadm"},
        {"command":"addautoadmidia"},
        {"command":"listautoadm"},
        {"command":"delautoadm"},
        {"command":"autorespostas"},
        {"command":"autorepo"},
    ] },
    { title: "MODOS & ATIVAÇÕES", icon: "✨", entries: [
        {"command":"autodl"},
        {"command":"minmessage"},
        {"command":"assistente"},
        {"command":"modobn"},
        {"command":"modoparceria"},
        {"command":"modorpg"},
        {"command":"modolite"},
        {"command":"bemvindo"},
        {"command":"saida"},
        {"command":"autosticker"},
        {"command":"soadm"},
        {"command":"cmdlimit"},
        {"command":"fotomenugrupo"},
        {"command":"nomegp"},
        {"command":"infoperso"},
    ] },
];

export default async function menuadm(prefix, _botName = "SHOGUN", userName = "Usuário", options = {}) {
    return renderShogunMenu({
        intro: "Cuide do grupo sem perder o clima da conversa.",
        footer: "Ajuste com intenção. Um bom grupo começa no cuidado.",
        options,
        title: "ADMINISTRAÇÃO", prefix, userName,
        sections: prepareMenuSections(sections, options),
    });
}
