import { prepareMenuSections, renderShogunMenu } from "./presentation.js";

const sections = [
    { title: "PERFIL & STATUS", icon: "👤", optionKey: "profileMenuTitle", entries: [
        {"command":"perfilrpg"},
        {"command":"carteira"},
        {"command":"toprpg"},
        {"command":"rankglobal"},
        {"command":"ranklvl"},
        {"command":"inv"},
        {"command":"equipamentos"},
        {"command":"conquistas"},
    ] },
    { title: "EVOLUÇÃO & PRESTÍGIO", icon: "⚔️", optionKey: "evolutionMenuTitle", entries: [
        {"command":"evoluir"},
        {"command":"prestige"},
        {"command":"streak"},
        {"command":"reivindicar"},
        {"command":"speedup"},
    ] },
    { title: "ECONOMIA & FINANÇAS", icon: "🪙", optionKey: "economyMenuTitle", entries: [
        {"command":"dep","arguments":"<valor|all>"},
        {"command":"sacar","arguments":"<valor|all>"},
        {"command":"pix","arguments":"@user <valor>"},
        {"command":"loja"},
        {"command":"comprar","arguments":"<item>"},
        {"command":"vender","arguments":"<item> <qtd>"},
        {"command":"vagas"},
        {"command":"emprego","arguments":"<vaga>"},
        {"command":"demitir"},
        {"command":"habilidades"},
        {"command":"desafiosemanal"},
        {"command":"desafiomensal"},
    ] },
    { title: "INVESTIMENTOS & BOLSA", icon: "🪙", optionKey: "investmentMenuTitle", entries: [
        {"command":"investir"},
        {"command":"investir","arguments":"<ação> <qtd>"},
        {"command":"sell","arguments":"<ação> <qtd>"},
    ] },
    { title: "CASSINO & APOSTAS", icon: "🪙", optionKey: "gamblingMenuTitle", entries: [
        {"command":"dados","arguments":"<valor>"},
        {"command":"coinflip","arguments":"<cara|coroa> <valor>"},
        {"command":"crash","arguments":"<valor>"},
        {"command":"slots","arguments":"<valor>"},
        {"command":"apostar","arguments":"<valor>"},
        {"command":"roleta","arguments":"<valor> <cor>"},
        {"command":"blackjack","arguments":"<valor>"},
        {"command":"loteria"},
        {"command":"loteria","arguments":"comprar <qtd>"},
        {"command":"corrida","arguments":"<valor> <cavalo>"},
        {"command":"leilao"},
        {"command":"topriqueza"},
    ] },
    { title: "ATIVIDADES DIÁRIAS", icon: "📝", optionKey: "activitiesMenuTitle", entries: [
        {"command":"diario"},
        {"command":"work"},
        {"command":"mine"},
        {"command":"fish"},
        {"command":"coletar"},
        {"command":"colher"},
        {"command":"caçar"},
        {"command":"plantar","arguments":"<planta>"},
        {"command":"cultivar","arguments":"<planta>"},
        {"command":"plantacao"},
        {"command":"cook","arguments":"<receita>"},
        {"command":"receitas"},
        {"command":"ingredientes"},
        {"command":"eat","arguments":"<comida>"},
        {"command":"vendercomida","arguments":"<item>"},
        {"command":"sementes"},
    ] },
    { title: "AVENTURA & EXPLORAÇÃO", icon: "⚔️", optionKey: "adventureMenuTitle", entries: [
        {"command":"explore"},
        {"command":"masmorra"},
        {"command":"bossrpg"},
        {"command":"eventos"},
    ] },
    { title: "DUNGEONS & RAIDS", icon: "⚔️", entries: [
        {"command":"dungeon","description":"Listar dungeons"},
        {"command":"dungeon","arguments":"criar <tipo>"},
        {"command":"dungeon","arguments":"entrar <id>"},
        {"command":"dungeon","arguments":"iniciar"},
        {"command":"dungeon","arguments":"sair"},
    ] },
    { title: "CLASSES & PROFISSÕES", icon: "⚔️", entries: [
        {"command":"class","description":"Ver classes"},
        {"command":"class","arguments":"<nome>","description":"Escolher uma classe."},
    ] },
    { title: "CASA", icon: "🏡", entries: [
        {"command":"casa","description":"Ver sua casa"},
        {"command":"casa","arguments":"comprar <tipo>"},
        {"command":"casa","arguments":"coletar"},
        {"command":"casa","arguments":"decorar <item>"},
    ] },
    { title: "MERCADO DE JOGADORES", icon: "🪙", entries: [
        {"command":"auction","description":"Ver itens"},
        {"command":"auction","arguments":"vender <item> <preço>"},
        {"command":"auction","arguments":"comprar <nº>"},
        {"command":"auction","arguments":"meus"},
        {"command":"auction","arguments":"cancelar <nº>"},
    ] },
    { title: "MERCADO GERAL", icon: "🪙", entries: [
        {"command":"mercado"},
        {"command":"listar","arguments":"<item> <preço>"},
        {"command":"cmerc","arguments":"<nº>"},
        {"command":"meusan"},
        {"command":"cancelar","arguments":"<nº>"},
    ] },
    { title: "COMBATE & BATALHAS", icon: "⚔️", optionKey: "combatMenuTitle", entries: [
        {"command":"duelrpg","arguments":"@user"},
        {"command":"arena"},
        {"command":"torneio"},
        {"command":"assaltar","arguments":"@user"},
        {"command":"crime"},
        {"command":"guerra"},
        {"command":"desafio"},
    ] },
    { title: "CRIAÇÃO & EQUIPAMENTOS", icon: "✨", optionKey: "craftingMenuTitle", entries: [
        {"command":"forge","arguments":"<item>"},
        {"command":"enchant"},
        {"command":"dismantle","arguments":"<item>"},
        {"command":"reparar","arguments":"<item>"},
        {"command":"materiais"},
        {"command":"precos"},
    ] },
    { title: "SOCIAL & INTERAÇÕES", icon: "🎲", optionKey: "socialMenuTitle", entries: [
        {"command":"casar","arguments":"@user"},
        {"command":"divorciar"},
        {"command":"namorar","arguments":"@user"},
        {"command":"terminar"},
        {"command":"relacionamento"},
        {"command":"casais"},
        {"command":"abracarrpg","arguments":"@user"},
        {"command":"beijarrpg","arguments":"@user"},
        {"command":"baterrpg","arguments":"@user"},
        {"command":"proteger","arguments":"@user"},
    ] },
    { title: "FAMÍLIA & ADOÇÃO", icon: "🫶", optionKey: "familyMenuTitle", entries: [
        {"command":"familia"},
        {"command":"adotaruser","arguments":"@user"},
        {"command":"deserdar","arguments":"@user"},
        {"command":"arvore"},
    ] },
    { title: "CLÃ & COMUNIDADE", icon: "✨", optionKey: "guildMenuTitle", entries: [
        {"command":"criarcla","arguments":"<nome>"},
        {"command":"cla"},
        {"command":"convidar","arguments":"@user"},
        {"command":"sair"},
        {"command":"aceitarconvite","arguments":"<clanId|nome>"},
        {"command":"recusarconvite","arguments":"<clanId|nome>"},
        {"command":"expulsar","arguments":"@user"},
        {"command":"rmconvite","arguments":"@user"},
    ] },
    { title: "MISSÕES & CONQUISTAS", icon: "🏆", optionKey: "questMenuTitle", entries: [
        {"command":"missoes"},
        {"command":"conquistas"},
    ] },
    { title: "PETS & COMPANHEIROS", icon: "🐾", optionKey: "petsMenuTitle", entries: [
        {"command":"pets"},
        {"command":"adotar","arguments":"<pet>"},
        {"command":"feed","arguments":"<nº>"},
        {"command":"train","arguments":"<nº>"},
        {"command":"evolve","arguments":"<nº>"},
        {"command":"petbattle","arguments":"<nº>"},
        {"command":"renamepet","arguments":"<nº> <nome>"},
        {"command":"petbet","arguments":"<valor> <nº> @user"},
        {"command":"equippet","arguments":"<nº> <nome do item>"},
        {"command":"unequippet","arguments":"<nº> <slot?>"},
    ] },
    { title: "REPUTAÇÃO & FAMA", icon: "✨", optionKey: "reputationMenuTitle", entries: [
        {"command":"rep"},
        {"command":"vote","arguments":"@user"},
    ] },
    { title: "EVENTOS", icon: "✨", optionKey: "eventsMenuTitle", entries: [
        {"command":"eventos"},
    ] },
    { title: "LOJA PREMIUM", icon: "🪙", optionKey: "premiumMenuTitle", entries: [
        {"command":"lojapremium"},
        {"command":"comprarpremium","arguments":"<item>"},
        {"command":"boost"},
        {"command":"propriedades"},
        {"command":"cprop","arguments":"<id>"},
        {"command":"cprops"},
        {"command":"tributos"},
        {"command":"meustats"},
        {"command":"doar","arguments":"<valor>"},
        {"command":"presente","arguments":"@user <item>"},
    ] },
    { title: "GESTÃO DO RPG", icon: "⚔️", optionKey: "adminMenuTitle", entries: [
        {"command":"rpgadd","arguments":"@user <valor>"},
        {"command":"rpgremove","arguments":"@user <valor>"},
        {"command":"rpgsetlevel","arguments":"@user <nivel>"},
        {"command":"rpgadditem","arguments":"@user <item> <qtd>"},
        {"command":"rpgremoveitem","arguments":"@user <item> <qtd>"},
        {"command":"rpgresetplayer","arguments":"@user"},
        {"command":"rpgresetglobal","arguments":"confirmar"},
        {"command":"rpgstats"},
    ] },
];

export default async function menuRPG(prefix, _botName = "SHOGUN", userName = "Usuário", options = {}) {
    return renderShogunMenu({
        intro: "Sua história ainda tem muito mapa pela frente.",
        footer: "Consulte sua ficha com #prefix#perfilrpg antes da aventura.",
        options,
        title: "RPG", prefix, userName,
        sections: prepareMenuSections(sections, options),
    });
}
