// Gerado das famílias top-level e descrições dos menus; teste de fechamento acompanha o runtime.
export const ASSISTANT_COMMAND_FAMILIES = [
    [
        "tavern",
        "campo",
        "render",
        "renderizar",
        "partida",
        "mulligan",
        "atacar",
        "poder",
        "fim",
        "desistir"
    ],
    [
        "roles",
        "role.lista",
        "listaroles"
    ],
    [
        "role.criar"
    ],
    [
        "role.alterar"
    ],
    [
        "role.excluir"
    ],
    [
        "role.vou"
    ],
    [
        "role.nvou"
    ],
    [
        "role",
        "role.confirmados",
        "role.participantes",
        "role.info"
    ],
    [
        "menurpg",
        "rpg"
    ],
    [
        "menunexo"
    ],
    [
        "lembrete",
        "lembrar"
    ],
    [
        "meuslembretes",
        "listalembretes"
    ],
    [
        "apagalembrete",
        "removerlembrete"
    ],
    [
        "modorpg",
        "rpgmode"
    ],
    [
        "perfilrpg",
        "carteira",
        "banco",
        "depositar",
        "dep",
        "sacar",
        "saque",
        "transferir",
        "pix",
        "loja",
        "lojarps",
        "comprar",
        "buy",
        "inventario",
        "inv",
        "apostar",
        "bet",
        "slots",
        "minerar",
        "mine",
        "trabalhar",
        "work",
        "emprego",
        "vagas",
        "demitir",
        "pescar",
        "fish",
        "explorar",
        "explore",
        "cacar",
        "caçar",
        "hunt",
        "mercado",
        "listar",
        "comprarmercado",
        "cmerc",
        "meusanuncios",
        "meusan",
        "cancelar",
        "propriedades",
        "comprarpropriedade",
        "cprop",
        "coletarpropriedades",
        "cprops",
        "habilidades",
        "desafiosemanal",
        "desafiomensal",
        "materiais",
        "precos",
        "preços",
        "vender",
        "reparar",
        "desafio",
        "forjar",
        "forge",
        "crime",
        "assaltar",
        "roubar",
        "cozinhar",
        "cook",
        "receitas",
        "plantar",
        "cultivar",
        "plant",
        "farm",
        "colher",
        "coletar",
        "harvest",
        "plantacao",
        "plantação",
        "horta",
        "comer",
        "eat",
        "vendercomida",
        "ingredientes",
        "sementes",
        "toprpg",
        "ranklevel",
        "ranklvl",
        "rankinglevel",
        "levels",
        "toplevels",
        "diario",
        "daily",
        "resetrpg"
    ],
    [
        "equipamentos",
        "gear",
        "equip"
    ],
    [
        "conquistas",
        "achievements",
        "medalhas"
    ],
    [
        "pets",
        "meuspets"
    ],
    [
        "adotar",
        "adopt"
    ],
    [
        "alimentar",
        "feed"
    ],
    [
        "treinar",
        "train"
    ],
    [
        "evoluirpet",
        "evolve"
    ],
    [
        "renomearpet",
        "renamepet"
    ],
    [
        "batalhapet",
        "petbattle"
    ],
    [
        "apostarpet",
        "petbet"
    ],
    [
        "equippet",
        "equiparpet"
    ],
    [
        "unequippet",
        "desequiparpet"
    ],
    [
        "equipar",
        "equip"
    ],
    [
        "desequipar",
        "unequip"
    ],
    [
        "masmorrasolo",
        "dungeonsolo",
        "dg"
    ],
    [
        "cheferpg",
        "bossrpg",
        "bossfight"
    ],
    [
        "eventos",
        "events",
        "eventosrpg"
    ],
    [
        "duelarrpg",
        "duelorpg",
        "duelrpg"
    ],
    [
        "arena"
    ],
    [
        "encantar",
        "enchant"
    ],
    [
        "desmontar",
        "dismantle"
    ],
    [
        "classe",
        "class",
        "profissao"
    ],
    [
        "casa",
        "house",
        "lar"
    ],
    [
        "dungeon",
        "masmorra",
        "raid"
    ],
    [
        "mercadoplayer",
        "auction",
        "leilaoplayer"
    ],
    [
        "missoes",
        "quests",
        "missao"
    ],
    [
        "guerra",
        "war",
        "guerracla"
    ],
    [
        "criarcla",
        "criarclã"
    ],
    [
        "cla",
        "claninfo"
    ],
    [
        "convidar",
        "invite",
        "convite"
    ],
    [
        "rmconvite",
        "removerconvite"
    ],
    [
        "sair"
    ],
    [
        "aceitarconvite",
        "aceitarrpg"
    ],
    [
        "recusarconvite",
        "recusar"
    ],
    [
        "expulsar",
        "kickcla"
    ],
    [
        "familia",
        "family"
    ],
    [
        "adotaruser",
        "adotarfilho"
    ],
    [
        "deserdar",
        "desherdar",
        "removerfilho"
    ],
    [
        "arvore",
        "familytree"
    ],
    [
        "torneio",
        "tournament"
    ],
    [
        "abracarrpg",
        "hugrpg"
    ],
    [
        "beijarrpg",
        "kissrpg"
    ],
    [
        "baterrpg",
        "taparpg",
        "slaprpg"
    ],
    [
        "proteger",
        "protect"
    ],
    [
        "reputacao",
        "rep",
        "reputation"
    ],
    [
        "votar",
        "vote"
    ],
    [
        "rankglobal",
        "globalrank",
        "toprpgglobal",
        "topglobal"
    ],
    [
        "rpgadd",
        "rpgaddmoney",
        "adicionardinheiro"
    ],
    [
        "rpgremove",
        "rpgremovemoney",
        "removerdinheiro"
    ],
    [
        "rpgsetlevel",
        "setlevel",
        "definirnivelrpg"
    ],
    [
        "rpgadditem",
        "adicionaritem"
    ],
    [
        "rpgremoveitem",
        "removeritem"
    ],
    [
        "rpgresetplayer",
        "resetarjogador"
    ],
    [
        "rpgresetglobal",
        "resetrpgglobal"
    ],
    [
        "rpgstats",
        "rpgstatistics",
        "estatisticasrpg"
    ],
    [
        "lojapremium",
        "premiumshop",
        "lojadeluxo"
    ],
    [
        "comprarpremium",
        "buypremium"
    ],
    [
        "roleta",
        "roulette"
    ],
    [
        "blackjack",
        "bj",
        "21"
    ],
    [
        "slots",
        "slotmachine",
        "cacaniquel"
    ],
    [
        "loteria",
        "lottery",
        "mega"
    ],
    [
        "corrida",
        "horserace",
        "cavalos"
    ],
    [
        "leilao",
        "leilaorpg",
        "leiloar"
    ],
    [
        "topriqueza",
        "toprich",
        "maiores"
    ],
    [
        "boost",
        "buff",
        "impulsionar"
    ],
    [
        "tributos",
        "impostos",
        "taxes"
    ],
    [
        "doar",
        "donate",
        "doacao"
    ],
    [
        "presente",
        "gift"
    ],
    [
        "meustats",
        "mystats",
        "statsrpg"
    ],
    [
        "evoluir",
        "evolucao",
        "prestige"
    ],
    [
        "investir",
        "invest"
    ],
    [
        "vender",
        "sell"
    ],
    [
        "dados",
        "dice"
    ],
    [
        "coinflip",
        "moeda"
    ],
    [
        "crash"
    ],
    [
        "streak",
        "serie"
    ],
    [
        "reivindicar",
        "claim"
    ],
    [
        "speedup",
        "boyvoice",
        "vozmenino",
        "womenvoice",
        "vozmulher",
        "manvoice",
        "vozhomem",
        "childvoice",
        "vozcrianca",
        "vozeco",
        "eco",
        "slowvoice",
        "vozlenta",
        "audiolento",
        "fastvoice",
        "vozrapida",
        "audiorapido",
        "cavevoice",
        "vozcaverna",
        "bass",
        "bass2",
        "bass3",
        "volumeboost",
        "aumentarvolume",
        "reverb",
        "overdrive",
        "equalizer",
        "equalizar",
        "reverse",
        "audioreverso",
        "pitch",
        "flanger",
        "grave",
        "vozgrave",
        "chorus",
        "phaser",
        "tremolo",
        "vibrato",
        "lowpass"
    ],
    [
        "videorapido",
        "fastvid",
        "videoslow",
        "slowvid",
        "reversevid",
        "videolento",
        "videoreverso",
        "videoloop",
        "videomudo",
        "videobw",
        "pretoebranco",
        "tomp3",
        "sepia",
        "espelhar",
        "rotacionar",
        "mirror",
        "rotate"
    ],
    [
        "gemma"
    ],
    [
        "phi",
        "phi3"
    ],
    [
        "qwen2"
    ],
    [
        "qwen",
        "qwen3"
    ],
    [
        "llama",
        "llama3"
    ],
    [
        "baichuan",
        "baichuan2"
    ],
    [
        "marin"
    ],
    [
        "kimi",
        "kimik2"
    ],
    [
        "mistral"
    ],
    [
        "magistral"
    ],
    [
        "rakutenai",
        "rocket"
    ],
    [
        "yi"
    ],
    [
        "gemma2"
    ],
    [
        "swallow"
    ],
    [
        "falcon"
    ],
    [
        "qwencoder"
    ],
    [
        "codegemma"
    ],
    [
        "resumir"
    ],
    [
        "resumirurl"
    ],
    [
        "ideias",
        "ideia"
    ],
    [
        "explicar",
        "explique"
    ],
    [
        "corrigir",
        "correcao"
    ],
    [
        "resumirchat",
        "resumirgrupo",
        "resumirconversa"
    ],
    [
        "historia",
        "story",
        "gerarhistoria"
    ],
    [
        "recomendar",
        "recomendacao",
        "recomendação",
        "suggest"
    ],
    [
        "wordle",
        "palavra"
    ],
    [
        "quiz",
        "trivia",
        "pergunta",
        "quizfilme",
        "cinequiz",
        "moviequiz"
    ],
    [
        "forca",
        "hangman"
    ],
    [
        "digitar",
        "typing",
        "digitacao"
    ],
    [
        "batalhanaval",
        "batalha",
        "naval"
    ],
    [
        "stop",
        "adedonha"
    ],
    [
        "anagrama"
    ],
    [
        "dueloquiz",
        "duelo"
    ],
    [
        "cacapalavras",
        "cacapalavra",
        "caca"
    ],
    [
        "verificarurl",
        "checkurl",
        "urlsafe",
        "linkseguro"
    ],
    [
        "clima",
        "tempo",
        "weather",
        "previsao"
    ],
    [
        "hora",
        "fuso",
        "horario",
        "timezone"
    ],
    [
        "aniversario",
        "niver",
        "birthday"
    ],
    [
        "groupstats",
        "estatisticas",
        "statsgrupo"
    ],
    [
        "cog"
    ],
    [
        "tradutor",
        "translator"
    ],
    [
        "qrcode"
    ],
    [
        "wikipedia"
    ],
    [
        "dicionario",
        "dictionary"
    ],
    [
        "updates"
    ],
    [
        "addsubdono"
    ],
    [
        "remsubdono",
        "rmsubdono",
        "delsubdono"
    ],
    [
        "listasubdonos",
        "listsubdonos"
    ],
    [
        "addsubbot"
    ],
    [
        "removesubbot",
        "delsubbot",
        "rmsubbot"
    ],
    [
        "listarsubbots",
        "listsubbots",
        "subbots"
    ],
    [
        "conectarsubbot",
        "reconnectsubbot"
    ],
    [
        "gerarcodigo",
        "pairingcode",
        "codigosubbot"
    ],
    [
        "cmdlimitar",
        "cmdlimit",
        "limitarcmd"
    ],
    [
        "cmddeslimitar",
        "cmdremovelimit",
        "rmcmdlimit"
    ],
    [
        "cmdlimites",
        "cmdlimits",
        "listcmdlimites"
    ],
    [
        "viewmsg"
    ],
    [
        "atualizar",
        "update",
        "atualizarbot"
    ],
    [
        "reiniciar",
        "restart",
        "reboot"
    ],
    [
        "leveling"
    ],
    [
        "level"
    ],
    [
        "addxp"
    ],
    [
        "delxp"
    ],
    [
        "dayfree"
    ],
    [
        "addautoresponse",
        "addauto"
    ],
    [
        "addautomedia",
        "addautomidia"
    ],
    [
        "addautoadm",
        "addautoadmin"
    ],
    [
        "addautoadmidia",
        "addautoadmmidia"
    ],
    [
        "listautoresponses",
        "listauto"
    ],
    [
        "listautoadm",
        "listautoadmin"
    ],
    [
        "delautoresponse",
        "delauto"
    ],
    [
        "delautoadm",
        "delautoadmin"
    ],
    [
        "autoresponses",
        "autorespostas"
    ],
    [
        "addnoprefix",
        "addnopref"
    ],
    [
        "listnoprefix",
        "listnopref"
    ],
    [
        "delnoprefix",
        "delnopref"
    ],
    [
        "addalias"
    ],
    [
        "listalias"
    ],
    [
        "delalias"
    ],
    [
        "addcmd",
        "adicionarcmd"
    ],
    [
        "edcmd",
        "editcmd"
    ],
    [
        "edcmdmidia",
        "editcmdmidia"
    ],
    [
        "addcmdmidia",
        "addcmdmedia"
    ],
    [
        "listcmd",
        "listarcmd",
        "comandospersonalizados"
    ],
    [
        "delcmd",
        "removercmd"
    ],
    [
        "testcmd",
        "testarcmd"
    ],
    [
        "addblackglobal"
    ],
    [
        "rmblackglobal"
    ],
    [
        "listblackglobal"
    ],
    [
        "encurtalink",
        "tinyurl"
    ],
    [
        "nick",
        "gerarnick",
        "nickgenerator"
    ],
    [
        "printsite",
        "ssweb"
    ],
    [
        "upload",
        "imgpralink",
        "videopralink",
        "gerarlink"
    ],
    [
        "verificar",
        "checklink",
        "scanlink",
        "urlscan"
    ],
    [
        "horamundial",
        "worldtime",
        "fusohorario",
        "horariomundial"
    ],
    [
        "clima2",
        "tempo2",
        "weather2",
        "previsao2"
    ],
    [
        "mcplugin",
        "mcplugins"
    ],
    [
        "play",
        "ytmp3"
    ],
    [
        "spotifydl",
        "spotify"
    ],
    [
        "play2",
        "playspotify"
    ],
    [
        "soundclouddl",
        "soundcloud"
    ],
    [
        "play3",
        "playsoundcloud"
    ],
    [
        "playvid",
        "ytmp4"
    ],
    [
        "letra",
        "lyrics"
    ],
    [
        "tiktok",
        "tiktokaudio",
        "tiktokvideo",
        "tiktoks",
        "tiktoksearch",
        "ttk",
        "tkk"
    ],
    [
        "facebook",
        "fb",
        "fbdl",
        "facebookdl"
    ],
    [
        "instagram",
        "igdl",
        "ig",
        "instavideo",
        "igstory"
    ],
    [
        "kwai"
    ],
    [
        "gdrive",
        "googledrive",
        "drive",
        "gd"
    ],
    [
        "mediafire",
        "mf"
    ],
    [
        "twitter",
        "twitterdl",
        "twt",
        "x",
        "xdl"
    ],
    [
        "google",
        "pesquisar",
        "buscar",
        "search"
    ],
    [
        "noticias",
        "news",
        "noticia"
    ],
    [
        "pinterest",
        "pin"
    ],
    [
        "zipbot",
        "zip-bot",
        "botzip",
        "bot-zip",
        "downloadbot",
        "download-bot"
    ],
    [
        "gitbot",
        "git-bot",
        "github",
        "git-hub",
        "repo",
        "repositorio",
        "source",
        "sourcecode",
        "source-code"
    ],
    [
        "menu",
        "help",
        "comandos",
        "commands"
    ],
    [
        "alteradores",
        "menualterador",
        "menualteradores",
        "changersmenu",
        "changers"
    ],
    [
        "menushogun"
    ],
    [
        "menulogo",
        "menulogos"
    ],
    [
        "menubn",
        "menubrincadeira",
        "menubrincadeiras",
        "gamemenu"
    ],
    [
        "menudown",
        "menudownload",
        "menudownloads",
        "downmenu",
        "downloadmenu"
    ],
    [
        "ferramentas",
        "menuferramentas",
        "menuferramenta",
        "toolsmenu",
        "tools"
    ],
    [
        "menuadm",
        "menuadmin",
        "menuadmins",
        "admmenu"
    ],
    [
        "menumembros",
        "menumemb",
        "menugeral",
        "membmenu",
        "membermenu"
    ],
    [
        "configcmdnotfound",
        "setcmdmsg"
    ],
    [
        "tutorial",
        "guia",
        "ajuda"
    ],
    [
        "menudono",
        "ownermenu"
    ],
    [
        "stickermenu",
        "menusticker",
        "menufig"
    ],
    [
        "antipv3"
    ],
    [
        "antipv2"
    ],
    [
        "antipv4"
    ],
    [
        "antipvmessage",
        "antipvmsg"
    ],
    [
        "antipv"
    ],
    [
        "entrar"
    ],
    [
        "sairgp"
    ],
    [
        "tm"
    ],
    [
        "inscrevertm",
        "inscrevertm2"
    ],
    [
        "desinscrever",
        "desinscrevertm",
        "cancelartm"
    ],
    [
        "tm2"
    ],
    [
        "statustm",
        "statustm2"
    ],
    [
        "reviverqr"
    ],
    [
        "cases"
    ],
    [
        "getcase"
    ],
    [
        "boton",
        "botoff"
    ],
    [
        "blockcmdg"
    ],
    [
        "unblockcmdg"
    ],
    [
        "blockuserg"
    ],
    [
        "unblockuserg"
    ],
    [
        "listblocks"
    ],
    [
        "seradm",
        "sermembro"
    ],
    [
        "defmsgpromo"
    ],
    [
        "sendmsgpromo"
    ],
    [
        "listmsgpromo"
    ],
    [
        "prefixo",
        "prefix"
    ],
    [
        "numerodono",
        "numero-dono"
    ],
    [
        "nomedono",
        "nome-dono"
    ],
    [
        "nomebot",
        "botname",
        "nome-bot"
    ],
    [
        "setnvidia"
    ],
    [
        "modeloconversa",
        "modeloshogun"
    ],
    [
        "fotomenu",
        "videomenu",
        "mediamenu",
        "midiamenu"
    ],
    [
        "audiomenu",
        "menuaudio",
        "setmenuaudio"
    ],
    [
        "lermais",
        "lermaismenus",
        "menulermais"
    ],
    [
        "fotobot",
        "fotoperfil",
        "setppbot",
        "perfilbot",
        "avatarbot"
    ],
    [
        "personalizargrupo",
        "ativarperso"
    ],
    [
        "fotomenugrupo",
        "setmenupic"
    ],
    [
        "removerfotomenu",
        "resetfotomenu"
    ],
    [
        "nomegrupo",
        "nomebotgrupo",
        "setbotname"
    ],
    [
        "removernome",
        "resetnome"
    ],
    [
        "infoperso",
        "personalizacao"
    ],
    [
        "setborda",
        "setbordatopo",
        "settopborder"
    ],
    [
        "setbordafim",
        "setbottomborder",
        "setbordabaixo"
    ],
    [
        "setbordameio",
        "setmiddleborder",
        "setbordamiddle"
    ],
    [
        "setitemicon",
        "seticoneitem",
        "setitem"
    ],
    [
        "setseparador",
        "setseparatoricon",
        "seticoneseparador"
    ],
    [
        "settitleicon",
        "seticonetitulo",
        "settitulo"
    ],
    [
        "setheader",
        "setcabecalho",
        "setheadermenu"
    ],
    [
        "resetdesign",
        "resetarmenu",
        "resetdesignmenu"
    ],
    [
        "designmenu",
        "menudesign",
        "verdesign",
        "configmenu"
    ],
    [
        "listagp",
        "listgp"
    ],
    [
        "listbangp"
    ],
    [
        "bangp",
        "unbangp",
        "desbangp"
    ],
    [
        "gruposbot"
    ],
    [
        "sairgp"
    ],
    [
        "blockbotgp",
        "unblockbotgp",
        "desbloquearbotgp"
    ],
    [
        "resetgold"
    ],
    [
        "addindicacao",
        "addindicar",
        "addindica"
    ],
    [
        "topindica",
        "topindicacao",
        "rankindicacao",
        "rankindicacoes"
    ],
    [
        "delindicacao",
        "rmindicacao",
        "removerindicacao"
    ],
    [
        "darkgreen",
        "glitch",
        "write",
        "advanced",
        "typography",
        "pixel",
        "neon",
        "flag",
        "americanflag",
        "deleting"
    ],
    [
        "pornhub",
        "avengers",
        "graffiti",
        "captainamerica",
        "stone3d",
        "neon2",
        "thor",
        "amongus",
        "deadpool",
        "blackpink"
    ],
    [
        "rvisu",
        "open",
        "revelar"
    ],
    [
        "limpardb"
    ],
    [
        "mantercontador",
        "preservarcontador"
    ],
    [
        "limparrank"
    ],
    [
        "resetrank"
    ],
    [
        "limparrankg"
    ],
    [
        "rankativos",
        "rankativo"
    ],
    [
        "rankinativos",
        "rankinativo"
    ],
    [
        "checkativo"
    ],
    [
        "atividade"
    ],
    [
        "totalcmd",
        "totalcomando"
    ],
    [
        "meustatus"
    ],
    [
        "infoserver"
    ],
    [
        "statusbot",
        "infobot",
        "botinfo"
    ],
    [
        "iaclear",
        "limparhist"
    ],
    [
        "topcmd",
        "topcmds",
        "comandosmaisusados"
    ],
    [
        "cmdinfo",
        "comandoinfo"
    ],
    [
        "statusgp",
        "dadosgp"
    ],
    [
        "dono"
    ],
    [
        "criador"
    ],
    [
        "diagnosticrpg",
        "repairdb",
        "fixdb"
    ],
    [
        "ping"
    ],
    [
        "toimg"
    ],
    [
        "togif"
    ],
    [
        "rmbg",
        "sbg",
        "sfundo"
    ],
    [
        "imagem"
    ],
    [
        "upscale"
    ],
    [
        "qc"
    ],
    [
        "emojimix"
    ],
    [
        "ttp"
    ],
    [
        "brat"
    ],
    [
        "bratvid"
    ],
    [
        "attp"
    ],
    [
        "st",
        "stk",
        "sticker",
        "s"
    ],
    [
        "st2",
        "stk2",
        "sticker2",
        "s2"
    ],
    [
        "figualeatoria",
        "randomsticker"
    ],
    [
        "rename",
        "renomear",
        "mudarpack"
    ],
    [
        "rgtake"
    ],
    [
        "take"
    ],
    [
        "figurinhas",
        "stickerpack",
        "packfig"
    ],
    [
        "mention"
    ],
    [
        "deletar",
        "delete",
        "del",
        "d"
    ],
    [
        "blockuser"
    ],
    [
        "unblockuser"
    ],
    [
        "listblocksgp",
        "blocklist"
    ],
    [
        "banir",
        "ban",
        "b",
        "kick"
    ],
    [
        "ban2",
        "banir2"
    ],
    [
        "bam",
        "banfake"
    ],
    [
        "setbammsg",
        "editarbam"
    ],
    [
        "verbammsg",
        "verbam"
    ],
    [
        "resetbammsg",
        "resetarbam"
    ],
    [
        "linkgp",
        "linkgroup"
    ],
    [
        "solicitacoes",
        "pendentes",
        "requests"
    ],
    [
        "aprovar",
        "aceitar",
        "approve"
    ],
    [
        "recusarsolic",
        "recusarsolicitacao",
        "reject"
    ],
    [
        "autoaceitarsolic",
        "autoaprovar",
        "autoacceptr"
    ],
    [
        "captchasolic",
        "captcha",
        "captcharequests"
    ],
    [
        "x9"
    ],
    [
        "promover",
        "promote"
    ],
    [
        "rebaixar",
        "demote"
    ],
    [
        "setname",
        "nomegp",
        "mudarnome",
        "alterarnome",
        "renomeargrupo"
    ],
    [
        "setdesc",
        "descgrupo",
        "mudardesc",
        "alterardesc",
        "descricao"
    ],
    [
        "setfoto",
        "fotogrupo",
        "mudarfoto",
        "alterarfoto",
        "fotogp"
    ],
    [
        "marcar",
        "mark"
    ],
    [
        "grupo",
        "gp",
        "group"
    ],
    [
        "opengp",
        "abrirgp"
    ],
    [
        "closegp",
        "fechargp"
    ],
    [
        "automsg"
    ],
    [
        "chaveamento"
    ],
    [
        "sorteionum"
    ],
    [
        "sorteionome"
    ],
    [
        "sorteio"
    ],
    [
        "totag",
        "cita",
        "hidetag"
    ],
    [
        "antilinkhard"
    ],
    [
        "divdono"
    ],
    [
        "setdiv"
    ],
    [
        "div",
        "divulgar"
    ],
    [
        "antibotao",
        "antibtn"
    ],
    [
        "antistatus"
    ],
    [
        "antidelete"
    ],
    [
        "autodl",
        "autodown"
    ],
    [
        "antidoc"
    ],
    [
        "limitmessage"
    ],
    [
        "dellimitmessage"
    ],
    [
        "setprefix"
    ],
    [
        "antiflood"
    ],
    [
        "antispamcmd"
    ],
    [
        "antiloc"
    ],
    [
        "modoadulto",
        "ia18",
        "modo18",
        "adulto"
    ],
    [
        "modobrincadeira",
        "modobrincadeiras",
        "modobn",
        "gamemode"
    ],
    [
        "bemvindo",
        "bv",
        "boasvindas",
        "welcome"
    ],
    [
        "banghost"
    ],
    [
        "fotobv",
        "welcomeimg",
        "setfotobv"
    ],
    [
        "bannerbv",
        "setbannerbv"
    ],
    [
        "fotosaida",
        "fotosaiu",
        "imgsaiu",
        "exitimg",
        "setfotosaida"
    ],
    [
        "bannersaiu",
        "bannersaida",
        "setbannersaiu"
    ],
    [
        "limpar",
        "clean"
    ],
    [
        "antibanmarcar",
        "protecaomarcar"
    ],
    [
        "removerfotobv",
        "rmfotobv",
        "delfotobv",
        "rmwelcomeimg"
    ],
    [
        "removerfotosaiu",
        "rmfotosaiu",
        "delfotosaiu",
        "rmexitimg"
    ],
    [
        "configsaida",
        "textsaiu",
        "legendasaiu",
        "exitmsg"
    ],
    [
        "saida",
        "exit"
    ],
    [
        "parcerias",
        "partnerships"
    ],
    [
        "addparceria",
        "addpartnership"
    ],
    [
        "delparceria",
        "delpartnership"
    ],
    [
        "modoparceria"
    ],
    [
        "antifig"
    ],
    [
        "addblacklist",
        "blacklist"
    ],
    [
        "delblacklist",
        "unblacklist"
    ],
    [
        "listblacklist"
    ],
    [
        "adv",
        "advertir",
        "warning"
    ],
    [
        "removeradv",
        "rmadv",
        "unwarning"
    ],
    [
        "listadv",
        "warninglist"
    ],
    [
        "suporte",
        "ticketsuporte",
        "suporteticket",
        "ticket"
    ],
    [
        "ticketaceitar",
        "aceitarticket",
        "suporteaceitar",
        "ticket.aceitar"
    ],
    [
        "soadm",
        "onlyadm",
        "soadmin"
    ],
    [
        "modolite",
        "litemode"
    ],
    [
        "modoliteglobal"
    ],
    [
        "antilinkgp"
    ],
    [
        "antilinkcanal",
        "antilinkch"
    ],
    [
        "antilinksoft"
    ],
    [
        "antiporn"
    ],
    [
        "autosticker"
    ],
    [
        "autorepo",
        "autoresposta"
    ],
    [
        "assistente",
        "assistent"
    ],
    [
        "antigore"
    ],
    [
        "legendabv",
        "textbv",
        "welcomemsg"
    ],
    [
        "mute",
        "mutar"
    ],
    [
        "desmute",
        "desmutar",
        "unmute"
    ],
    [
        "mute2",
        "mutar2"
    ],
    [
        "desmute2",
        "desmutar2",
        "unmute2"
    ],
    [
        "blockcmd"
    ],
    [
        "unblockcmd"
    ],
    [
        "ttt",
        "jogodavelha",
        "tictactoe"
    ],
    [
        "connect4",
        "c4",
        "ligue4"
    ],
    [
        "uno"
    ],
    [
        "memoria",
        "memory"
    ],
    [
        "conquistasbn",
        "achievementsbn",
        "medalhasbn"
    ],
    [
        "caixa",
        "box"
    ],
    [
        "presentebn",
        "giftbn"
    ],
    [
        "inventario",
        "inventory"
    ],
    [
        "repbn",
        "reputacaobn"
    ],
    [
        "toprep",
        "rankrep"
    ],
    [
        "denunciar",
        "report"
    ],
    [
        "denuncias",
        "reports"
    ],
    [
        "qrcodebn",
        "gerarqrbn"
    ],
    [
        "lerqr",
        "readqr",
        "scanqr"
    ],
    [
        "nota",
        "note"
    ],
    [
        "notas",
        "notes"
    ],
    [
        "calc",
        "calcular",
        "calculadora"
    ],
    [
        "cortaraudio",
        "cutaudio"
    ],
    [
        "velocidade",
        "speed"
    ],
    [
        "reversobn",
        "reversebn"
    ],
    [
        "bassbn",
        "bassboostbn"
    ],
    [
        "normalizar",
        "normalize"
    ],
    [
        "cortarvideo",
        "cortarvid",
        "cutvideo"
    ],
    [
        "horoscopo",
        "signo"
    ],
    [
        "signos"
    ],
    [
        "debater",
        "debate"
    ],
    [
        "historiainterativa",
        "storyinteractive",
        "aventura"
    ],
    [
        "antitoxic",
        "antitóxico"
    ],
    [
        "antipalavra",
        "antiword"
    ],
    [
        "chance"
    ],
    [
        "quando"
    ],
    [
        "brincadeira"
    ],
    [
        "namoro",
        "namorar"
    ],
    [
        "casamento",
        "casar"
    ],
    [
        "relacionamento"
    ],
    [
        "casais",
        "couples",
        "listacasais"
    ],
    [
        "divorciar",
        "divorcio",
        "terminar",
        "termino",
        "terminarelacionamento"
    ],
    [
        "trair",
        "traicao"
    ],
    [
        "historicotraicao",
        "historicotraicoes",
        "historicodetraicao"
    ],
    [
        "casal"
    ],
    [
        "shipo"
    ],
    [
        "sn"
    ],
    [
        "sorte"
    ],
    [
        "admins",
        "admin",
        "adm",
        "adms"
    ],
    [
        "perfil"
    ],
    [
        "conquista",
        "achievement"
    ],
    [
        "ppt"
    ],
    [
        "eununca"
    ],
    [
        "vab"
    ],
    [
        "conselho"
    ],
    [
        "conselhobiblico",
        "versiculo",
        "biblia"
    ],
    [
        "cantada",
        "cantadas"
    ],
    [
        "piada",
        "piadas"
    ],
    [
        "charada",
        "enigma"
    ],
    [
        "motivacional",
        "motivacao",
        "frasemotivacional"
    ],
    [
        "elogio",
        "elogiar"
    ],
    [
        "reflexao",
        "pensamento"
    ],
    [
        "fato",
        "fatocurioso",
        "curiosidade"
    ],
    [
        "surubao",
        "suruba"
    ],
    [
        "suicidio"
    ],
    [
        "gay",
        "burro",
        "inteligente",
        "otaku",
        "fiel",
        "infiel",
        "corno",
        "gado",
        "gostoso",
        "feio",
        "rico",
        "pobre",
        "pirocudo",
        "pirokudo",
        "ladrao",
        "safado",
        "vesgo",
        "bebado",
        "machista",
        "homofobico",
        "racista",
        "chato",
        "sortudo",
        "azarado",
        "forte",
        "fraco",
        "pegador",
        "otario",
        "macho",
        "bobo",
        "nerd",
        "preguicoso",
        "trabalhador",
        "brabo",
        "lindo",
        "malandro",
        "simpatico",
        "engracado",
        "charmoso",
        "misterioso",
        "carinhoso",
        "desumilde",
        "humilde",
        "ciumento",
        "corajoso",
        "covarde",
        "esperto",
        "talarico",
        "chorao",
        "brincalhao",
        "bolsonarista",
        "petista",
        "comunista",
        "lulista",
        "traidor",
        "bandido",
        "cachorro",
        "vagabundo",
        "pilantra",
        "mito",
        "padrao",
        "comedia",
        "psicopata",
        "fortao",
        "magrelo",
        "bombado",
        "chefe",
        "presidente",
        "rei",
        "patrao",
        "playboy",
        "zueiro",
        "gamer",
        "programador",
        "visionario",
        "billionario",
        "poderoso",
        "vencedor",
        "senhor",
        "fofoqueiro",
        "dorminhoco",
        "comilao",
        "sedentario",
        "atleta",
        "estudioso",
        "romantico",
        "extrovertido",
        "introvertido",
        "calmo",
        "nervoso",
        "organizado",
        "bagunceiro",
        "economico",
        "gastador",
        "saudavel",
        "doente",
        "supersticioso",
        "cetico",
        "religioso",
        "ateu",
        "tradicional",
        "moderno",
        "conservador",
        "liberal",
        "patriotico",
        "cosmopolita",
        "rural",
        "urbano",
        "aventureiro",
        "caseiro",
        "viajante",
        "local",
        "global",
        "tecnologico",
        "analogico",
        "digital",
        "offline",
        "online",
        "social",
        "antisocial",
        "popular",
        "solitario",
        "lider",
        "seguidor",
        "independente",
        "dependente",
        "criativo",
        "pratico",
        "sonhador",
        "realista",
        "otimista",
        "pessimista",
        "confiante",
        "inseguro",
        "maduro",
        "infantil",
        "serio",
        "sortudo2",
        "zueira",
        "viaja nte",
        "responsavel",
        "irresponsavel"
    ],
    [
        "lesbica",
        "burra",
        "corna",
        "gostosa",
        "feia",
        "rica",
        "bucetuda",
        "ladra",
        "safada",
        "vesga",
        "bebada",
        "homofobica",
        "chata",
        "sortuda",
        "azarada",
        "fraca",
        "pegadora",
        "otaria",
        "boba",
        "preguicosa",
        "trabalhadora",
        "braba",
        "linda",
        "malandra",
        "simpatica",
        "engracada",
        "charmosa",
        "misteriosa",
        "carinhosa",
        "ciumenta",
        "corajosa",
        "esperta",
        "talarica",
        "chorona",
        "brincalhona",
        "traidora",
        "bandida",
        "cachorra",
        "vagabunda",
        "fortona",
        "magrela",
        "bombada",
        "presidenta",
        "rainha",
        "patroa",
        "programadora",
        "visionaria",
        "bilionaria",
        "poderosa",
        "vencedora",
        "senhora",
        "fofoqueira",
        "dorminhoca",
        "comilona",
        "sedentaria",
        "estudiosa",
        "romantica",
        "extrovertida",
        "introvertida",
        "calma",
        "nervosa",
        "organizada",
        "bagunceira",
        "economica",
        "gastadora",
        "supersticiosa",
        "cetica",
        "religiosa",
        "ateia",
        "moderna",
        "conservadora",
        "patriotica",
        "urbana",
        "aventureira",
        "caseira",
        "tecnologica",
        "analogica",
        "solitaria",
        "seguidora",
        "criativa",
        "pratica",
        "sonhadora",
        "insegura",
        "madura",
        "seria"
    ],
    [
        "rankgay",
        "rankburro",
        "rankinteligente",
        "rankotaku",
        "rankfiel",
        "rankinfiel",
        "rankcorno",
        "rankgado",
        "rankgostoso",
        "rankrico",
        "rankpobre",
        "rankforte",
        "rankpegador",
        "rankmacho",
        "ranknerd",
        "ranktrabalhador",
        "rankbrabo",
        "ranklindo",
        "rankmalandro",
        "rankengracado",
        "rankcharmoso",
        "rankvisionario",
        "rankpoderoso",
        "rankvencedor",
        "rankgays",
        "rankburros",
        "rankinteligentes",
        "rankotakus",
        "rankfiels",
        "rankinfieis",
        "rankcornos",
        "rankgados",
        "rankgostosos",
        "rankricos",
        "rankpobres",
        "rankfortes",
        "rankpegadores",
        "rankmachos",
        "ranknerds",
        "ranktrabalhadores",
        "rankbrabos",
        "ranklindos",
        "rankmalandros",
        "rankengracados",
        "rankcharmosos",
        "rankvisionarios",
        "rankpoderosos",
        "rankvencedores"
    ],
    [
        "ranklesbica",
        "rankburra",
        "rankcorna",
        "rankgada",
        "rankgostosa",
        "rankrica",
        "rankpegadora",
        "ranktrabalhadora",
        "rankbraba",
        "ranklinda",
        "rankmalandra",
        "rankengracada",
        "rankcharmosa",
        "rankvisionaria",
        "rankpoderosa",
        "rankvencedora",
        "ranklesbicas",
        "rankburras",
        "rankcornas",
        "rankgads",
        "rankgostosas",
        "rankricas",
        "rankpegadoras",
        "ranktrabalhadoras",
        "rankbrabas",
        "ranklindas",
        "rankmalandras",
        "rankengracadas",
        "rankcharmosas",
        "rankvisionarias",
        "rankpoderosas",
        "rankvencedoras"
    ],
    [
        "chute",
        "chutar",
        "tapa",
        "soco",
        "socar",
        "beijo",
        "beijar",
        "beijob",
        "beijarb",
        "abraco",
        "abracar",
        "mata",
        "matar",
        "tapar",
        "goza",
        "gozar",
        "mamar",
        "mamada",
        "cafune",
        "morder",
        "mordida",
        "lamber",
        "lambida",
        "explodir",
        "sexo",
        "tomate"
    ],
    [
        "afk"
    ],
    [
        "voltei"
    ],
    [
        "regras"
    ],
    [
        "addregra",
        "addrule"
    ],
    [
        "delregra",
        "delrule"
    ],
    [
        "addmod"
    ],
    [
        "delmod"
    ],
    [
        "listmods",
        "modlist"
    ],
    [
        "grantmodcmd",
        "addmodcmd"
    ],
    [
        "revokemodcmd",
        "delmodcmd"
    ],
    [
        "listmodcmds"
    ],
    [
        "wl.add",
        "wladd",
        "addwhitelist"
    ],
    [
        "wl.remove",
        "wlremove",
        "removewhitelist"
    ],
    [
        "wl.lista",
        "wllist",
        "listawhitelist",
        "whitelistlista"
    ],
    [
        "minmessage"
    ],
    [
        "nuke"
    ],
    [
        "msgprefix"
    ],
    [
        "msgboton"
    ],
    [
        "addreact"
    ],
    [
        "delreact"
    ],
    [
        "listreact"
    ],
    [
        "freetemu"
    ],
    [
        "cachedebug",
        "debugcache"
    ],
    [
        "horarios",
        "horariopagante",
        "sinais"
    ],
    [
        "autohorarios"
    ],
    [
        "rentalstats"
    ],
    [
        "rentaltest"
    ],
    [
        "rentalconfig"
    ],
    [
        "rentalclean"
    ]
];
export const ASSISTANT_COMMAND_DESCRIPTIONS = {
    "menu": "Exibir o menu principal de comandos.",
    "lembrete": "Criar um lembrete com prazo e mensagem informados.",
    "lembrar": "Criar um lembrete com prazo e mensagem informados.",
    "cortarvideo": "Recortar o vídeo entre os tempos indicados.",
    "tomp3": "Extrair o áudio do vídeo em MP3.",
    "rmbg": "Remover o fundo da imagem.",
    "upscale": "Aumentar a resolução da imagem.",
    "cortaraudio": "Recortar o áudio entre os tempos indicados.",
    "velocidade": "Alterar a velocidade do áudio.",
    "speed": "Alterar a velocidade do áudio.",
    "normalizar": "Normalizar o volume do áudio.",
    "gerarnick": "Gerar um nick estilizado.",
    "ssweb": "Capturar uma página a partir do link.",
    "qrcode": "Gerar um QR code com o texto informado.",
    "lerqr": "Ler o QR code da imagem respondida.",
    "calc": "Converter um valor entre unidades.",
    "notas": "Listar suas notas pessoais.",
    "nota": "Criar ou gerenciar uma nota pessoal; ao salvar, use add antes do texto.",
    "verificar": "Consultar informações de segurança do link.",
    "hora": "Consultar o horário da cidade ou país.",
    "clima": "Consultar o clima da cidade.",
    "dicionario": "Consultar o significado da palavra.",
    "tradutor": "Traduzir o texto informado.",
    "meuslembretes": "Consultar seus lembretes.",
    "menufig": "Criar figurinhas, remover fundos e editar créditos.",
    "menulogos": "Gerar logos com um ou dois textos.",
    "alteradores": "Cortar mídia e aplicar efeitos de áudio, vídeo e imagem.",
    "menudown": "Buscar músicas e baixar mídia ou arquivos por link.",
    "menubn": "Jogos, brincadeiras e interações entre membros.",
    "menurpg": "Personagens, economia, equipamentos e batalhas.",
    "menunexo": "Ativar o Nexo, criar personagem e jogar o tutorial.",
    "menumemb": "Perfil, atividade, conquistas e rankings dos membros.",
    "menushogun": "Resumir, explicar, revisar textos e escolher o modelo de IA.",
    "ferramentas": "Calculadora, tradução, notas, QR codes e lembretes.",
    "menuadm": "Moderação, proteções e configurações do grupo.",
    "menudono": "Configuração do bot, automações e controle da instância.",
    "ban": "Remover um membro do grupo.",
    "bam": "Simular um banimento.",
    "promover": "Tornar um membro administrador.",
    "rebaixar": "Remover o cargo de administrador.",
    "mute": "Silenciar um membro.",
    "desmute": "Retirar o silenciamento de um membro.",
    "adv": "Registrar uma advertência.",
    "hidetag": "Enviar um aviso a todos os membros do grupo sem exibir a lista de menções.",
    "setdesc": "Alterar a descrição do grupo para o texto informado.",
    "listadv": "Consultar as advertências registradas.",
    "atividade": "Consultar a atividade de um membro.",
    "linkgp": "Consultar o link de convite do grupo.",
    "grupo": "Abrir ou fechar o envio de mensagens no grupo.",
    "opengp": "Agendar a abertura do grupo ou desativar o horário.",
    "closegp": "Agendar o fechamento do grupo ou desativar o horário.",
    "solicitacoes": "Listar pedidos de entrada no grupo.",
    "aprovar": "Aprovar todos os pedidos de entrada pendentes.",
    "recusarsolic": "Recusar um pedido de entrada.",
    "grantmodcmd": "Autorizar um comando para moderadores.",
    "listmodcmds": "Consultar comandos permitidos aos moderadores.",
    "antitoxic": "Ajustar a sensibilidade da detecção de mensagens tóxicas.",
    "antipalavra": "Ativar a proteção e gerenciar palavras bloqueadas.",
    "setprefix": "Alterar o prefixo do grupo.",
    "modolite": "Alternar o modo lite do grupo.",
    "soadm": "Restringir o uso de comandos aos administradores.",
    "tictactoe": "Desafiar um membro para o jogo da velha.",
    "connect4": "Desafiar um membro para o jogo de quatro em linha.",
    "memoria": "Jogar ou consultar o ranking de memória.",
    "wordle": "Tentar descobrir a palavra.",
    "forca": "Jogar forca.",
    "batalhanaval": "Desafiar um membro para batalha naval.",
    "dueloquiz": "Desafiar um membro para um duelo de perguntas.",
    "cacapalavras": "Jogar caça-palavras na dificuldade escolhida.",
    "ppt": "Jogar pedra, papel e tesoura.",
    "tutorial": "Usar uma técnica.",
    "prefixo": "Alterar o prefixo padrão do bot.",
    "numerodono": "Configurar o contato do dono da instância.",
    "nomebot": "Alterar o nome de exibição do bot.",
    "designmenu": "Consultar e configurar a aparência dos menus.",
    "resetdesign": "Restaurar o design padrão dos menus.",
    "addalias": "Cadastrar um nome alternativo para um comando.",
    "listalias": "Consultar os aliases cadastrados.",
    "cmdlimites": "Consultar os limites de uso dos comandos.",
    "listasubdonos": "Listar subdonos da instância.",
    "listprem": "Listar usuários premium.",
    "listarsubbots": "Consultar os sub-bots cadastrados.",
    "listblocks": "Consultar bloqueios globais.",
    "listagp": "Listar os grupos do bot.",
    "modoliteglobal": "Configurar o modo lite global.",
    "google": "Pesquisar na web.",
    "pesquisar": "Pesquisar na web pelo assunto informado.",
    "imagem": "Gerar uma imagem nova a partir da descrição informada.",
    "noticias": "Consultar notícias gerais ou sobre um assunto.",
    "apps": "Pesquisar aplicativos pelo nome.",
    "wikipedia": "Consultar um artigo sobre o assunto.",
    "letra": "Consultar a letra da música.",
    "play": "Buscar uma música e enviar o áudio.",
    "play2": "Buscar uma música e enviar o áudio por outro comando.",
    "spotify": "Baixar o áudio de uma faixa pelo link do Spotify.",
    "soundcloud": "Baixar o áudio pelo link do SoundCloud.",
    "playvid": "Buscar e enviar um vídeo.",
    "tiktok": "Baixar o vídeo pelo link do TikTok.",
    "instagram": "Baixar fotos, Reels ou carrosséis pelo link.",
    "kwai": "Baixar o vídeo pelo link do Kwai.",
    "igstory": "Solicitar o download de um story disponível pelo link.",
    "facebook": "Baixar o vídeo pelo link do Facebook.",
    "gdrive": "Baixar um arquivo público pelo link do Drive.",
    "mediafire": "Baixar um arquivo pelo link do MediaFire.",
    "twitter": "Baixar a mídia de uma publicação pelo link.",
    "pinterest": "Pesquisar imagens no Pinterest.",
    "mcplugin": "Pesquisar plugins de Minecraft.",
    "emojimix": "Combinar dois emojis em uma figurinha.",
    "ttp": "Criar uma figurinha de texto.",
    "attp": "Criar uma figurinha de texto animado.",
    "sticker": "Converter uma imagem ou um vídeo em figurinha.",
    "sticker2": "Converter imagem ou vídeo de até 9,9 segundos em figurinha.",
    "sbg": "Remover o fundo da imagem e enviar como figurinha.",
    "sfundo": "Remover o fundo da imagem e enviar como figurinha.",
    "qc": "Criar uma figurinha de mensagem.",
    "brat": "Criar uma figurinha de texto no estilo brat.",
    "bratvid": "Criar uma figurinha animada de texto no estilo brat.",
    "figualeatoria": "Enviar uma figurinha aleatória do acervo.",
    "figurinhas": "Enviar de 1 a 15 figurinhas; em grupos, a entrega é no privado.",
    "rename": "Alterar autor e pacote da figurinha respondida.",
    "rgtake": "Salvar autor e pacote no formato Autor/Pack.",
    "take": "Aplicar os créditos salvos à figurinha respondida.",
    "toimg": "Converter uma figurinha em imagem.",
    "perfil": "Consultar seu perfil.",
    "ping": "Consultar o tempo de resposta do bot.",
    "statusbot": "Consultar o estado do bot.",
    "statusgp": "Consultar informações do grupo.",
    "regras": "Consultar as regras do grupo.",
    "afk": "Registrar sua ausência.",
    "voltei": "Encerrar o estado de ausência.",
    "roles": "Consultar os eventos do grupo.",
    "role.vou": "Confirmar presença em um evento.",
    "role.nvou": "Informar que não participará de um evento.",
    "role.confirmados": "Consultar participantes confirmados.",
    "rankativo": "Consultar o ranking de atividade.",
    "topcmd": "Consultar os comandos mais usados.",
    "denunciar": "Registrar uma denúncia com o motivo.",
    "nexo": "Consultar a ajuda por categoria.",
    "entrar": "Criar personagem com Impulso e Cicatriz; origem automática.",
    "continuar": "Retomar uma escolha pendente.",
    "painel": "Ver o estado do Círculo com imagem.",
    "ficha": "Ver sua ficha com imagem.",
    "privado": "Escolher respostas no privado ou no grupo.",
    "cancelar": "Cancelar uma escolha pendente.",
    "combate": "Atacar um inimigo do combate.",
    "perfilrpg": "Consultar nível e atributos do personagem.",
    "carteira": "Consultar seu saldo no RPG.",
    "loja": "Exibir a loja do RPG.",
    "inventario": "Consultar os itens do inventário do RPG.",
    "minerar": "Minerar recursos no RPG.",
    "daily": "Receber a recompensa diária do RPG.",
    "diario": "Receber a recompensa diária do RPG.",
    "dados": "Apostar o valor informado em um jogo de dados do RPG.",
    "inv": "Consultar os itens do inventário.",
    "equipamentos": "Consultar seus equipamentos.",
    "dep": "Depositar moedas no banco do RPG.",
    "sacar": "Retirar moedas do banco do RPG.",
    "pix": "Transferir moedas para outro jogador.",
    "vagas": "Consultar vagas de emprego no RPG.",
    "emprego": "Escolher uma vaga de emprego.",
    "dungeon": "Sair da masmorra atual.",
    "class": "Escolher a classe do personagem.",
    "casa": "Decorar sua casa com o item indicado.",
    "auction": "Cancelar um dos seus anúncios.",
    "duelrpg": "Desafiar outro jogador para um duelo.",
    "forge": "Forjar o item indicado.",
    "criarcla": "Criar um clã com o nome indicado.",
    "missoes": "Consultar suas missões.",
    "pets": "Consultar seus pets.",
    "rpgresetplayer": "Zerar os dados do jogador indicado.",
    "rpgresetglobal": "Zerar os dados globais do RPG após confirmação.",
    "rpgstats": "Consultar estatísticas do RPG."
};
//# sourceMappingURL=command-catalog.js.map