const EFFECT_TYPES = new Set([
  'DAMAGE',
  'DAMAGE_HERO',
  'HEAL',
  'GAIN_ARMOR',
  'DRAW',
  'DISCARD',
  'SUMMON',
  'SUMMON_RANDOM',
  'BUFF_ATTACK',
  'BUFF_HEALTH',
  'BUFF_STATS',
  'SET_STATS',
  'DESTROY',
  'SILENCE',
  'RETURN_TO_HAND',
  'SHUFFLE_INTO_DECK',
  'DISCOUNT',
  'INCREASE_COST',
  'COPY',
  'RANDOM_TARGET',
  'APPLY_STATUS',
  'CREATE_CARD',
  'MODIFY_TERRAIN',
  'GAIN_MANA',
  'PEEK_TOP',
  'DISCOUNT_NEXT_SPELL'
]);

const EFFECT_TRIGGERS = new Set([
  'ON_PLAY',
  'ON_DEATH',
  'ON_TURN_START',
  'ON_TURN_END',
  'ON_ATTACK',
  'AFTER_ATTACK',
  'ON_DAMAGE',
  'AFTER_DAMAGE',
  'ON_DRAW',
  'ON_SUMMON',
  'ON_SPELL_CAST',
  'HERO_POWER_USED'
]);

const EFFECT_TARGETS = new Set([
  'SELF',
  'TARGET',
  'FRIENDLY_HERO',
  'ENEMY_HERO',
  'FRIENDLY_BOARD',
  'ALL_FRIENDLY_MINIONS',
  'ALL_ENEMY_MINIONS',
  'ALL_OTHER_ENEMIES',
  'RANDOM_ENEMY_MINION'
]);

export { EFFECT_TARGETS, EFFECT_TRIGGERS, EFFECT_TYPES };
